update

diff --git a/manifests/falco/logrotate/Dockerfile b/manifests/falco/logrotate/Dockerfile
--- a/manifests/falco/logrotate/Dockerfile
+++ b/manifests/falco/logrotate/Dockerfile
@@ -1,8 +1,6 @@
 FROM alpine:latest
 
 RUN apk add --no-cache logrotate
-RUN mkdir -p /var/lib/logrotate
 
-ENTRYPOINT ["logrotate"]
-CMD ["-s", "/var/lib/logrotate/logrotate.status", "/etc/logrotate.conf"]
+CMD ["sh", "-c", "while true; do logrotate -v /etc/logrotate.d/falco || echo 'logrotate failed'; sleep 3600; done"]
 
